services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - mynetwork

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mynetwork

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork: